name: RunsafeAuctionHouse
main: no.runsafe.auctionhouse.Plugin
version: 1.0.@BUILD@
author: Kruithne
description: Auction House System
commands:
  auction:
    description: Creates a new auction
    aliases: [/auc]
